### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [sashacravcenco/kinozal_bootstrap_template#1]
1)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/98830855-8c49fd00-2443-11eb-93ad-adea668cb716.png)

2)
задание отсутствует
https://sashacravcenco.github.io/kinozal_bootstrap_template/page.html
![image](https://user-images.githubusercontent.com/8464662/98830957-a84d9e80-2443-11eb-8bcc-09e4de57f08c.png)

3)
не работает
![image](https://user-images.githubusercontent.com/8464662/98831039-ba2f4180-2443-11eb-83b9-f581c36cfe63.png)

**Comment by sashacravcenco** [comment]
внесла правки
